# -*- coding: utf-8 -*-
"""automate_Muhammad_Ali_M

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0g3sj3oij_EAg5Nj5rn0sJANemHRYiw
"""

import os
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Struktur fungsi
def prep_data(input_path, output_path):
  print(f'Memuat data dari {input_path}...')

  # Validasi
  if not os.path.exists(input_path):
    print(f'Path {input_path} tidak ditemukan')
    return
  df = pd.read_csv(input_path)
  print('Dimensi data: ', df.shape)

  target = 'Potability'

  if target not in df.columns:
    print(f'Kolom target {target} tidak ditemukan')
    return
 # Pisahkan fitur dan target

  X = df.drop(columns=[target])
  y = df[target]
  print(f'Kolom target: {target}')

  # Menyimpan metadata
  feature = X.columns

  # Mengatasi nilai yang hilang dengan median
  imputer = SimpleImputer(strategy='median')
  X_imputer = imputer.fit_transform(X)

  # Melakukan standarisasi
  scaler = StandardScaler()
  X_scaled = scaler.fit_transform(X_imputer)

  # Membangung dataframe kembali
  X_df = pd.DataFrame(X_scaled, columns=feature)
  df_final = pd.concat([X_df, y], axis=1)

  # Penyimpanan
  os.makedirs(os.path.dirname(output_path), exist_ok=True)
  df_final.to_csv(output_path, index=False)

  print(f'Data berhasil disimpan ke {output_path}')
  print(f'Dimensi data: {df_final.shape}')
if __name__ == '__main__':
  input_data_csv = '/content/water_potability.csv'
  output_data_csv = '/content/water_potability_preprocessing.csv'
  prep_data(input_data_csv, output_data_csv)