name: water_potability_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - scikit-learn=1.5.0
  - pandas=2.2.0
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pip
  - pip:
    - mlflow==2.14.2
