name: water_potability_env_$(date +%s) 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - numpy=1.26.4
  - pandas=2.2.0
  - scikit-learn=1.5.0
  - matplotlib=3.8.3
  - seaborn=0.13.2
  - pip:
    - mlflow==2.14.2
